version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=bookstore
      - MYSQL_USER=bookstore_user
      - MYSQL_PASSWORD=bookstore_password
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_USER=bookstore_user
      - MYSQL_PASSWORD=bookstore_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

volumes:
  db-data:
