name: Java CI/CD with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml -DskipTests
    
    - name: Run Tests
      run: ./mvnw test
    
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: bookstore-jar
        path: target/bookstore.jar

  # Uncomment the deploy job when you have a deployment platform set up
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   
  #   steps:
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: bookstore-jar
  #       
  #   - name: Deploy to Production
  #     run: |
  #       # Add deployment commands here
  #       # Example for Railway:
  #       # curl -fsSL https://railway.app/install.sh | sh
  #       # railway up --detach
